version: '2'

networks:
  test:

services:
  ca_org5:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org5.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=15054
    ports:
      - "15054:15054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/org5:/etc/hyperledger/fabric-ca-server
    container_name: ca.org5.example.com
    hostname: ca.org5.example.com
    networks:
      - test
