version: '2'

networks:
  test:

services:
  ca_org6:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org6.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=17054
    ports:
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/org6:/etc/hyperledger/fabric-ca-server
    container_name: ca.org6.example.com
    hostname: ca.org6.example.com
    networks:
      - test